# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: Dominic Minischetti
title: Full Stack Developer
email: dominic.minischetti@gmail.com
website: www.minischetti.org

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: dominischetti
twitter_username: dominischetti
instagram_username: dminischetti
facebook_username: dominic.minischetti
# github_username:  sproogen
# stackoverflow_username: "00000001"
# youtube_username: globalmtb

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
about_title: About me
about_profile_image: images/IMG_4128.jpeg
about_content: | # this will include new lines to allow paragraphs
  Experienced Full Stack Developer with over 5 years # Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dominic Minischetti
title: PHP Backend Engineer
email: dominic.minischetti@gmail.com
website: www.minischetti.org
phone: (+1) 347 606 6909

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: dminischetti
github_username: dminischetti

# About Section
about_title: About Me
about_profile_image: images/IMG_4128.jpeg
about_content: |
  PHP Backend Engineer with over 5 years of experience in eCommerce, logistics, and web application development. Proven track record in building high-performance systems and optimizing database architectures. Skilled in agile methodologies and dedicated to clean, efficient code and exceptional user experiences.

content:
  - title: Professional Experience
    layout: list
    content:
      - layout: left
        title: Backend PHP Developer
        sub_title: BLOX Digital
        caption: July 2024 - Present
        description: |
            - Enhancing CMS for media clients, troubleshooting to optimize system reliability.
            - Collaborate with development teams to identify areas for improved system performance.

      - layout: left
        title: Backend PHP Developer
        sub_title: Appliances Connection
        caption: May 2022 - March 2024
        description: |
            - Built a Warehouse Management System (WMS) with PHP, JavaScript, and MySQL, improving inventory tracking and workflow efficiency.
            - Developed responsive interfaces for warehouse operations, enhancing team productivity.

      - layout: left
        title: Full Stack Developer
        sub_title: Kingsleague GmbH
        caption: August 2021 - May 2022
        description: |
            - Developed high-performance web applications with PHP, MySQL, Firebase, and Docker.
            - Streamlined deployments with Nginx and Docker, and automated testing with Python and Selenium.

      - layout: left
        title: Data Analyst & Database Administrator
        sub_title: Eiffel srl
        caption: November 2012 - October 2015
        description: |
            - Led SQL Server database administration, mentoring junior admins and implementing consolidated reporting solutions.
            - Improved data analysis by implementing SQL Server-based solutions for efficient data consolidation.

      - layout: left
        title: Data Analyst
        sub_title: Call2U
        caption: September 2010 - November 2012
        description: |
            - Diagnosed and resolved technical issues, ensuring smooth operations across software and hardware systems.
            - Maintained Service Manager instances and SQL Server backends for data integrity.

      - layout: left
        title: Frontend Developer
        sub_title: ASD Servizi
        caption: December 2006 - April 2008
        description: |
            - Built and managed websites and PHP applications, focusing on content management and web services.

  - title: Education
    layout: list
    content:
      - layout: left
        title: CUNY New York City College of Technology
        caption: 2020
        sub_title: Bachelor of Technology, Computer Information Systems (Database Track)
        description: |
          - GPA: 3.7/4. Specialized in Oracle SQL Developer, Microsoft SQL Server, and database management.

      - layout: left
        title: University of Bari, Italy
        caption: 2000
        sub_title: Coursework in Computer and Information Sciences
        description: |
          - Gained a foundational understanding of programming with Java, C++, and Python.

  - title: Certifications & Additional Courses
    layout: text
    content: |
        - <b>MongoDB University</b> - MongoDB Course, 2021
        - <b>NYC College of Technology</b> - Project Management, 2019

  - title: Technical Skills
    layout: text
    content: |
        - **Programming Languages**: PHP, Python, JavaScript
        - **Frameworks & Libraries**: Bootstrap, jQuery, Smarty
        - **Database Management**: SQL Server, MySQL, MariaDB, MongoDB
        - **DevOps Tools**: Docker, Nginx, Git, Jenkins
        - **API Development**: RESTful API design and integration
        - **Development Methodologies**: Agile (Kanban), OOP, MVC Architecture
        - **Operating Systems & Servers**: Linux, Apache, IIS, Windows

  - title: Soft Skills
    layout: text
    content: |
        - Collaborative and effective team player
        - Clear communicator with a focus on detail
        - Strong time management and organizational skills
        - Adaptable to new tools and technologies
        - Problem-solver with a results-driven mindset

  - title: Languages
    layout: text
    content: |
        - **Italian**: Native
        - **English**: Fluent
        - **Spanish**: Elementary

# Footer
footer_show_references: false
