baseURL = 'https://minischetti.org/'
title = "Dominic Minischetti"
theme = "PaperMod"
languageCode = "en-us"

[pagination]
  pagerSize = 10
  paginatePath = "page"

[params]
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  useHLJS = true
  themeVariant = "dark"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 3

[params.seo]
  description = "Dominic Minischetti's personal blog and portfolio"
  twitterHandle = "@dominischetti"  # Matches Twitter username
  facebookAppID = ""  # Optional, remove if not used

[outputs]
  home = ["HTML", "RSS", "JSON", "RobotsTXT"]

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"  # Choose from: monokai, dracula, github, etc.
    lineNos = true
    lineNumbersInTable = true

[minify]
  disableXML = true
  [minify.tdewolff]
    keepWhitespace = false

[caches]
  [caches.images]
    dir = ":cacheDir/images"
    maxAge = "24h"

  [caches.getjson]
    dir = ":cacheDir/json"
    maxAge = "1h"

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"