name: Deploy site + blog

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Costruisce SOLO il sito Hugo dentro /blog
      - name: Build Hugo (blog)
        run: hugo --minify --source blog --destination public/blog

      # Copia TUTTI i file root (index.html, CSS, immagini, ecc.)
      - name: Copy root files
        run: |
          mkdir -p public
          rsync -av --exclude='blog/' --exclude='.github/' ./ public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public