name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: ['blog/**']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build Hugo
        run: |
          cd blog
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/blog/"

      - name: Prepare Pages Structure
        run: |
          mkdir -p ./public
          # Copy root HTML files
          find . -maxdepth 1 -type f -name "*.html" -exec cp {} ./public/ \; || true
          find . -maxdepth 1 -type f -name "*.css" -exec cp {} ./public/ \; || true
          find . -maxdepth 1 -type f -name "*.js" -exec cp {} ./public/ \; || true
          
          # Copy root directories (assets, images, etc.)
          [ -d "./assets" ] && cp -r ./assets ./public/ || true
          [ -d "./images" ] && cp -r ./images ./public/ || true
          [ -d "./media" ] && cp -r ./media ./public/ || true
          
          # Copy section directories
          [ -d "./one" ] && cp -r ./one ./public/ || true
          [ -d "./two" ] && cp -r ./two ./public/ || true
          [ -d "./three" ] && cp -r ./three ./public/ || true
          
          # Copy Hugo output to blog subdirectory
          cp -r ./blog/public ./public/blog

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
