name: Deploy site + blog

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Build del blog Hugo dalla cartella /blog verso /public/blog
      - name: Build blog
        run: hugo --minify --source blog --destination public/blog

      # Copia TUTTI i file statici della root (index.html, CNAME, /static, ecc.) in /public
      - name: Copy root files
        run: |
          mkdir -p public
          [ -f index.html ] && cp -f index.html public/ || true
          [ -f CNAME ] && cp -f CNAME public/ || true
          [ -d static ] && rsync -av static/ public/ || true

      # (Debug utile) Mostra cosa stai pubblicando
      - name: List publish dir
        run: ls -R public

      # Crea l'artifact per Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4